### ISSUE TITLE
sanitization problem somewhere

### ISSUE THREAD

**Issue by TSTdoll** [myndzi/hdlink#1]
#### irc message

![](https://i.imgur.com/kVNeCdh.png)
#### shoutbox result

![](https://i.imgur.com/S14O3YZ.png)
#### discord result

![](https://i.imgur.com/zQiiIxW.png)

**Comment by myndzi** [comment]
Closing as irrelevant; seems to be a problem with discord itself. My best guess is that user references are by id always, and converted to the username on the client presentation layer -- and that this process is being interfered with by whatever escaping is being done to prevent rendering literal < > in the client.

**Comment by TSTdoll** [comment]
more testing.

#### irc message

![](https://i.imgur.com/xtxivMI.png)

#### shoutbox result

![](https://i.imgur.com/V5Vsscb.png)

#### discord result

![](https://i.imgur.com/D3c50iN.png)
